[2024-10-09T21:58:46.721+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-09T21:58:46.735+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_parquet_with_fdw.create_parquet_fdw_extension manual__2024-10-09T21:53:43.789984+00:00 [queued]>
[2024-10-09T21:58:46.742+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_parquet_with_fdw.create_parquet_fdw_extension manual__2024-10-09T21:53:43.789984+00:00 [queued]>
[2024-10-09T21:58:46.743+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-09T21:58:46.755+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): create_parquet_fdw_extension> on 2024-10-09 21:53:43.789984+00:00
[2024-10-09T21:58:46.760+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-09T21:58:46.762+0000] {standard_task_runner.py:72} INFO - Started process 7107 to run task
[2024-10-09T21:58:46.762+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_parquet_with_fdw', 'create_parquet_fdw_extension', 'manual__2024-10-09T21:53:43.789984+00:00', '--job-id', '1517', '--raw', '--subdir', 'DAGS_FOLDER/teste.py', '--cfg-path', '/tmp/tmpdxpdajl7']
[2024-10-09T21:58:46.764+0000] {standard_task_runner.py:105} INFO - Job 1517: Subtask create_parquet_fdw_extension
[2024-10-09T21:58:46.818+0000] {task_command.py:467} INFO - Running <TaskInstance: load_parquet_with_fdw.create_parquet_fdw_extension manual__2024-10-09T21:53:43.789984+00:00 [running]> on host 97b4e38b3eb9
[2024-10-09T21:58:47.020+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_parquet_with_fdw' AIRFLOW_CTX_TASK_ID='create_parquet_fdw_extension' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T21:53:43.789984+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-09T21:53:43.789984+00:00'
[2024-10-09T21:58:47.020+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-09T21:58:47.031+0000] {sql.py:266} INFO - Executing: CREATE EXTENSION IF NOT EXISTS parquet_fdw;
[2024-10-09T21:58:47.038+0000] {base.py:84} INFO - Retrieving connection 'postgres-***'
[2024-10-09T21:58:47.045+0000] {base.py:84} INFO - Retrieving connection 'postgres-***'
[2024-10-09T21:58:47.056+0000] {sql.py:509} INFO - Running statement: CREATE EXTENSION IF NOT EXISTS parquet_fdw;, parameters: None
[2024-10-09T21:58:47.060+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/share/postgresql/13/extension/parquet_fdw.control": No such file or directory

[2024-10-09T21:58:47.068+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=load_parquet_with_fdw, task_id=create_parquet_fdw_extension, run_id=manual__2024-10-09T21:53:43.789984+00:00, execution_date=20241009T215343, start_date=20241009T215846, end_date=20241009T215847
[2024-10-09T21:58:47.081+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-09T21:58:47.081+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1517 for task create_parquet_fdw_extension (could not open extension control file "/usr/share/postgresql/13/extension/parquet_fdw.control": No such file or directory
; 7107)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/share/postgresql/13/extension/parquet_fdw.control": No such file or directory

[2024-10-09T21:58:47.098+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-09T21:58:47.107+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-10-09T21:58:47.119+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-09T21:58:47.124+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
