[2024-10-16T18:32:12.972+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T18:32:12.987+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LoadWebScraping.submit_spark_job manual__2024-10-16T18:32:11.550553+00:00 [queued]>
[2024-10-16T18:32:12.994+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LoadWebScraping.submit_spark_job manual__2024-10-16T18:32:11.550553+00:00 [queued]>
[2024-10-16T18:32:12.994+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-16T18:32:13.155+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): submit_spark_job> on 2024-10-16 18:32:11.550553+00:00
[2024-10-16T18:32:13.161+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T18:32:13.163+0000] {standard_task_runner.py:72} INFO - Started process 270 to run task
[2024-10-16T18:32:13.163+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LoadWebScraping', 'submit_spark_job', 'manual__2024-10-16T18:32:11.550553+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/LoadWebScraping.py', '--cfg-path', '/tmp/tmpaywjonsd']
[2024-10-16T18:32:13.166+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask submit_spark_job
[2024-10-16T18:32:13.230+0000] {task_command.py:467} INFO - Running <TaskInstance: LoadWebScraping.submit_spark_job manual__2024-10-16T18:32:11.550553+00:00 [running]> on host dd1ffe4a61bb
[2024-10-16T18:32:13.482+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LoadWebScraping' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T18:32:11.550553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-16T18:32:11.550553+00:00'
[2024-10-16T18:32:13.483+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T18:32:13.494+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-16T18:32:13.494+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master spark://spark:7077 --driver-class-path /opt/***/jars/postgresql-42.5.0.jar --jars /opt/***/jars/postgresql-42.5.0.jar --name arrow-spark --deploy-mode client /opt/bitnami/spark/src/scripts_spark/LoadFileToDB.py']
[2024-10-16T18:32:13.503+0000] {subprocess.py:86} INFO - Output:
[2024-10-16T18:32:15.152+0000] {subprocess.py:93} INFO - 24/10/16 18:32:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-16T18:32:15.281+0000] {subprocess.py:93} INFO - 24/10/16 18:32:15 WARN DependencyUtils: Local jar /opt/***/jars/postgresql-42.5.0.jar does not exist, skipping.
[2024-10-16T18:32:16.461+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkContext: Running Spark version 3.5.2
[2024-10-16T18:32:16.461+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-10-16T18:32:16.462+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkContext: Java version 17.0.12
[2024-10-16T18:32:16.494+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO ResourceUtils: ==============================================================
[2024-10-16T18:32:16.495+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-16T18:32:16.496+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO ResourceUtils: ==============================================================
[2024-10-16T18:32:16.496+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkContext: Submitted application: LoadFileToDB
[2024-10-16T18:32:16.517+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-16T18:32:16.525+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO ResourceProfile: Limiting resource is cpu
[2024-10-16T18:32:16.526+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-16T18:32:16.572+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SecurityManager: Changing view acls to: ***
[2024-10-16T18:32:16.573+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SecurityManager: Changing modify acls to: ***
[2024-10-16T18:32:16.574+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SecurityManager: Changing view acls groups to:
[2024-10-16T18:32:16.574+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SecurityManager: Changing modify acls groups to:
[2024-10-16T18:32:16.575+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-16T18:32:16.740+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO Utils: Successfully started service 'sparkDriver' on port 42423.
[2024-10-16T18:32:16.764+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkEnv: Registering MapOutputTracker
[2024-10-16T18:32:16.792+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-16T18:32:16.805+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-16T18:32:16.806+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-16T18:32:16.810+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-16T18:32:16.826+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0660ec51-f2cc-4467-994b-edd48cc97cbd
[2024-10-16T18:32:16.837+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-16T18:32:16.848+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-16T18:32:16.972+0000] {subprocess.py:93} INFO - 24/10/16 18:32:16 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-16T18:32:17.104+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-16T18:32:17.180+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 ERROR SparkContext: Failed to add file:/opt/***/jars/postgresql-42.5.0.jar to Spark environment
[2024-10-16T18:32:17.182+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/***/jars/postgresql-42.5.0.jar not found
[2024-10-16T18:32:17.183+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:2095)
[2024-10-16T18:32:17.183+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2151)
[2024-10-16T18:32:17.184+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15(SparkContext.scala:521)
[2024-10-16T18:32:17.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$15$adapted(SparkContext.scala:521)
[2024-10-16T18:32:17.187+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2024-10-16T18:32:17.199+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2024-10-16T18:32:17.201+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2024-10-16T18:32:17.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:521)
[2024-10-16T18:32:17.204+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-10-16T18:32:17.209+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-16T18:32:17.213+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-16T18:32:17.214+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-16T18:32:17.216+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-16T18:32:17.216+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-16T18:32:17.217+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-16T18:32:17.219+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-16T18:32:17.224+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2024-10-16T18:32:17.230+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-16T18:32:17.231+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-16T18:32:17.231+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-16T18:32:17.232+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-16T18:32:17.232+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-16T18:32:17.294+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-10-16T18:32:17.339+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO TransportClientFactory: Successfully created connection to spark/172.18.0.6:7077 after 25 ms (0 ms spent in bootstraps)
[2024-10-16T18:32:17.464+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241016183217-0001
[2024-10-16T18:32:17.472+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241016183217-0001/0 on worker-20241016182719-172.18.0.3-37523 (172.18.0.3:37523) with 6 core(s)
[2024-10-16T18:32:17.472+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO StandaloneSchedulerBackend: Granted executor ID app-20241016183217-0001/0 on hostPort 172.18.0.3:37523 with 6 core(s), 1024.0 MiB RAM
[2024-10-16T18:32:17.492+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34669.
[2024-10-16T18:32:17.495+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO NettyBlockTransferService: Server created on dd1ffe4a61bb:34669
[2024-10-16T18:32:17.495+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-16T18:32:17.506+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, dd1ffe4a61bb, 34669, None)
[2024-10-16T18:32:17.511+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO BlockManagerMasterEndpoint: Registering block manager dd1ffe4a61bb:34669 with 434.4 MiB RAM, BlockManagerId(driver, dd1ffe4a61bb, 34669, None)
[2024-10-16T18:32:17.512+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/0 is now RUNNING
[2024-10-16T18:32:17.514+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, dd1ffe4a61bb, 34669, None)
[2024-10-16T18:32:17.516+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, dd1ffe4a61bb, 34669, None)
[2024-10-16T18:32:17.832+0000] {subprocess.py:93} INFO - 24/10/16 18:32:17 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-16T18:32:18.099+0000] {subprocess.py:93} INFO - 24/10/16 18:32:18 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-10-16T18:32:18.103+0000] {subprocess.py:93} INFO - 24/10/16 18:32:18 INFO SharedState: Warehouse path is 'file:/tmp/***tmphcztfsap/spark-warehouse'.
[2024-10-16T18:32:19.104+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO InMemoryFileIndex: It took 72 ms to list leaf files for 1 paths.
[2024-10-16T18:32:19.480+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO SparkContext: Starting job: parquet at NativeMethodAccessorImpl.java:0
[2024-10-16T18:32:19.494+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO DAGScheduler: Got job 0 (parquet at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-10-16T18:32:19.495+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO DAGScheduler: Final stage: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0)
[2024-10-16T18:32:19.496+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO DAGScheduler: Parents of final stage: List()
[2024-10-16T18:32:19.498+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO DAGScheduler: Missing parents: List()
[2024-10-16T18:32:19.502+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-10-16T18:32:19.565+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 103.6 KiB, free 434.3 MiB)
[2024-10-16T18:32:19.591+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 37.5 KiB, free 434.3 MiB)
[2024-10-16T18:32:19.596+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on dd1ffe4a61bb:34669 (size: 37.5 KiB, free: 434.4 MiB)
[2024-10-16T18:32:19.599+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2024-10-16T18:32:19.616+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-10-16T18:32:19.618+0000] {subprocess.py:93} INFO - 24/10/16 18:32:19 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2024-10-16T18:32:20.135+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.3:40592) with ID 0,  ResourceProfileId 0
[2024-10-16T18:32:20.200+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.3:38905 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.3, 38905, None)
[2024-10-16T18:32:20.256+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.3, executor 0, partition 0, PROCESS_LOCAL, 9238 bytes)
[2024-10-16T18:32:20.431+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/0 is now EXITED (Command exited with code 50)
[2024-10-16T18:32:20.431+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO StandaloneSchedulerBackend: Executor app-20241016183217-0001/0 removed: Command exited with code 50
[2024-10-16T18:32:20.433+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241016183217-0001/1 on worker-20241016182719-172.18.0.3-37523 (172.18.0.3:37523) with 6 core(s)
[2024-10-16T18:32:20.433+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO StandaloneSchedulerBackend: Granted executor ID app-20241016183217-0001/1 on hostPort 172.18.0.3:37523 with 6 core(s), 1024.0 MiB RAM
[2024-10-16T18:32:20.438+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 ERROR TaskSchedulerImpl: Lost executor 0 on 172.18.0.3: Command exited with code 50
[2024-10-16T18:32:20.453+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.18.0.3 executor 0): ExecutorLostFailure (executor 0 exited caused by one of the running tasks) Reason: Command exited with code 50
[2024-10-16T18:32:20.460+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO DAGScheduler: Executor lost: 0 (epoch 0)
[2024-10-16T18:32:20.461+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/1 is now RUNNING
[2024-10-16T18:32:20.465+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO BlockManagerMasterEndpoint: Trying to remove executor 0 from BlockManagerMaster.
[2024-10-16T18:32:20.468+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(0, 172.18.0.3, 38905, None)
[2024-10-16T18:32:20.469+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO BlockManagerMaster: Removed 0 successfully in removeExecutor
[2024-10-16T18:32:20.469+0000] {subprocess.py:93} INFO - 24/10/16 18:32:20 INFO DAGScheduler: Shuffle files lost for executor: 0 (epoch 0)
[2024-10-16T18:32:22.438+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.3:40624) with ID 1,  ResourceProfileId 0
[2024-10-16T18:32:22.496+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.3:36603 with 434.4 MiB RAM, BlockManagerId(1, 172.18.0.3, 36603, None)
[2024-10-16T18:32:22.531+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.18.0.3, executor 1, partition 0, PROCESS_LOCAL, 9238 bytes)
[2024-10-16T18:32:22.659+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/1 is now EXITED (Command exited with code 50)
[2024-10-16T18:32:22.660+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO StandaloneSchedulerBackend: Executor app-20241016183217-0001/1 removed: Command exited with code 50
[2024-10-16T18:32:22.661+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 ERROR TaskSchedulerImpl: Lost executor 1 on 172.18.0.3: Command exited with code 50
[2024-10-16T18:32:22.662+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 WARN TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) (172.18.0.3 executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Command exited with code 50
[2024-10-16T18:32:22.663+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241016183217-0001/2 on worker-20241016182719-172.18.0.3-37523 (172.18.0.3:37523) with 6 core(s)
[2024-10-16T18:32:22.663+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO StandaloneSchedulerBackend: Granted executor ID app-20241016183217-0001/2 on hostPort 172.18.0.3:37523 with 6 core(s), 1024.0 MiB RAM
[2024-10-16T18:32:22.664+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO DAGScheduler: Executor lost: 1 (epoch 1)
[2024-10-16T18:32:22.665+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO BlockManagerMasterEndpoint: Trying to remove executor 1 from BlockManagerMaster.
[2024-10-16T18:32:22.666+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(1, 172.18.0.3, 36603, None)
[2024-10-16T18:32:22.666+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO BlockManagerMaster: Removed 1 successfully in removeExecutor
[2024-10-16T18:32:22.667+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO DAGScheduler: Shuffle files lost for executor: 1 (epoch 1)
[2024-10-16T18:32:22.684+0000] {subprocess.py:93} INFO - 24/10/16 18:32:22 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/2 is now RUNNING
[2024-10-16T18:32:24.389+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.3:40632) with ID 2,  ResourceProfileId 0
[2024-10-16T18:32:24.433+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.3:37883 with 434.4 MiB RAM, BlockManagerId(2, 172.18.0.3, 37883, None)
[2024-10-16T18:32:24.465+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.18.0.3, executor 2, partition 0, PROCESS_LOCAL, 9238 bytes)
[2024-10-16T18:32:24.590+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/2 is now EXITED (Command exited with code 50)
[2024-10-16T18:32:24.593+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO StandaloneSchedulerBackend: Executor app-20241016183217-0001/2 removed: Command exited with code 50
[2024-10-16T18:32:24.594+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 ERROR TaskSchedulerImpl: Lost executor 2 on 172.18.0.3: Command exited with code 50
[2024-10-16T18:32:24.595+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241016183217-0001/3 on worker-20241016182719-172.18.0.3-37523 (172.18.0.3:37523) with 6 core(s)
[2024-10-16T18:32:24.595+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO StandaloneSchedulerBackend: Granted executor ID app-20241016183217-0001/3 on hostPort 172.18.0.3:37523 with 6 core(s), 1024.0 MiB RAM
[2024-10-16T18:32:24.596+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 WARN TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) (172.18.0.3 executor 2): ExecutorLostFailure (executor 2 exited caused by one of the running tasks) Reason: Command exited with code 50
[2024-10-16T18:32:24.597+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO DAGScheduler: Executor lost: 2 (epoch 2)
[2024-10-16T18:32:24.597+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO BlockManagerMasterEndpoint: Trying to remove executor 2 from BlockManagerMaster.
[2024-10-16T18:32:24.598+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(2, 172.18.0.3, 37883, None)
[2024-10-16T18:32:24.599+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO BlockManagerMaster: Removed 2 successfully in removeExecutor
[2024-10-16T18:32:24.599+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO DAGScheduler: Shuffle files lost for executor: 2 (epoch 2)
[2024-10-16T18:32:24.619+0000] {subprocess.py:93} INFO - 24/10/16 18:32:24 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/3 is now RUNNING
[2024-10-16T18:32:26.608+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.3:50438) with ID 3,  ResourceProfileId 0
[2024-10-16T18:32:26.703+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.3:36109 with 434.4 MiB RAM, BlockManagerId(3, 172.18.0.3, 36109, None)
[2024-10-16T18:32:26.770+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.18.0.3, executor 3, partition 0, PROCESS_LOCAL, 9238 bytes)
[2024-10-16T18:32:26.990+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/3 is now EXITED (Command exited with code 50)
[2024-10-16T18:32:26.991+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO StandaloneSchedulerBackend: Executor app-20241016183217-0001/3 removed: Command exited with code 50
[2024-10-16T18:32:26.995+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 ERROR TaskSchedulerImpl: Lost executor 3 on 172.18.0.3: Command exited with code 50
[2024-10-16T18:32:26.996+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 WARN TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.3 executor 3): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Command exited with code 50
[2024-10-16T18:32:26.997+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241016183217-0001/4 on worker-20241016182719-172.18.0.3-37523 (172.18.0.3:37523) with 6 core(s)
[2024-10-16T18:32:26.998+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO StandaloneSchedulerBackend: Granted executor ID app-20241016183217-0001/4 on hostPort 172.18.0.3:37523 with 6 core(s), 1024.0 MiB RAM
[2024-10-16T18:32:26.998+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2024-10-16T18:32:26.999+0000] {subprocess.py:93} INFO - 24/10/16 18:32:26 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2024-10-16T18:32:27.002+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO TaskSchedulerImpl: Cancelling stage 0
[2024-10-16T18:32:27.003+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.3 executor 3): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Command exited with code 50
[2024-10-16T18:32:27.003+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2024-10-16T18:32:27.004+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO DAGScheduler: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0) failed in 7.481 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.3 executor 3): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Command exited with code 50
[2024-10-16T18:32:27.004+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2024-10-16T18:32:27.016+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO DAGScheduler: Executor lost: 3 (epoch 3)
[2024-10-16T18:32:27.018+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO DAGScheduler: Job 0 failed: parquet at NativeMethodAccessorImpl.java:0, took 7.535465 s
[2024-10-16T18:32:27.018+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO BlockManagerMasterEndpoint: Trying to remove executor 3 from BlockManagerMaster.
[2024-10-16T18:32:27.019+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(3, 172.18.0.3, 36109, None)
[2024-10-16T18:32:27.021+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO BlockManagerMaster: Removed 3 successfully in removeExecutor
[2024-10-16T18:32:27.021+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO DAGScheduler: Shuffle files lost for executor: 3 (epoch 3)
[2024-10-16T18:32:27.024+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241016183217-0001/4 is now RUNNING
[2024-10-16T18:32:27.101+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-16T18:32:27.106+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/src/scripts_spark/LoadFileToDB.py", line 9, in <module>
[2024-10-16T18:32:27.108+0000] {subprocess.py:93} INFO -     df = spark.read.parquet("/opt/***/datalake/silverzone/pichau_2024-10-15/dim_site.parquet")
[2024-10-16T18:32:27.109+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-16T18:32:27.109+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2024-10-16T18:32:27.110+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-10-16T18:32:27.110+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-10-16T18:32:27.111+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-10-16T18:32:27.116+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o27.parquet.
[2024-10-16T18:32:27.122+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.3 executor 3): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Command exited with code 50
[2024-10-16T18:32:27.123+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2024-10-16T18:32:27.123+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2024-10-16T18:32:27.124+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2024-10-16T18:32:27.124+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2024-10-16T18:32:27.124+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2024-10-16T18:32:27.125+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2024-10-16T18:32:27.125+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2024-10-16T18:32:27.125+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2024-10-16T18:32:27.126+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2024-10-16T18:32:27.126+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2024-10-16T18:32:27.127+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2024-10-16T18:32:27.127+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2024-10-16T18:32:27.127+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2024-10-16T18:32:27.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2024-10-16T18:32:27.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2024-10-16T18:32:27.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2024-10-16T18:32:27.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2024-10-16T18:32:27.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2024-10-16T18:32:27.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2024-10-16T18:32:27.130+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2024-10-16T18:32:27.130+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2458)
[2024-10-16T18:32:27.131+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1049)
[2024-10-16T18:32:27.131+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2024-10-16T18:32:27.132+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2024-10-16T18:32:27.141+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
[2024-10-16T18:32:27.141+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.collect(RDD.scala:1048)
[2024-10-16T18:32:27.142+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.mergeSchemasInParallel(SchemaMergeUtils.scala:74)
[2024-10-16T18:32:27.143+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.mergeSchemasInParallel(ParquetFileFormat.scala:497)
[2024-10-16T18:32:27.143+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$.inferSchema(ParquetUtils.scala:132)
[2024-10-16T18:32:27.144+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.inferSchema(ParquetFileFormat.scala:79)
[2024-10-16T18:32:27.144+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
[2024-10-16T18:32:27.145+0000] {subprocess.py:93} INFO - 	at scala.Option.orElse(Option.scala:447)
[2024-10-16T18:32:27.145+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
[2024-10-16T18:32:27.145+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
[2024-10-16T18:32:27.146+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2024-10-16T18:32:27.146+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2024-10-16T18:32:27.146+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2024-10-16T18:32:27.147+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2024-10-16T18:32:27.147+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2024-10-16T18:32:27.147+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-10-16T18:32:27.148+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-10-16T18:32:27.148+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-10-16T18:32:27.150+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-10-16T18:32:27.157+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-10-16T18:32:27.158+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-16T18:32:27.159+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2024-10-16T18:32:27.159+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-10-16T18:32:27.160+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-10-16T18:32:27.160+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-16T18:32:27.161+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-16T18:32:27.161+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-16T18:32:27.162+0000] {subprocess.py:93} INFO - 
[2024-10-16T18:32:27.230+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO SparkContext: Invoking stop() from shutdown hook
[2024-10-16T18:32:27.231+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-16T18:32:27.248+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO SparkUI: Stopped Spark web UI at http://dd1ffe4a61bb:4040
[2024-10-16T18:32:27.254+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-16T18:32:27.255+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-16T18:32:27.278+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-16T18:32:27.291+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO MemoryStore: MemoryStore cleared
[2024-10-16T18:32:27.291+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO BlockManager: BlockManager stopped
[2024-10-16T18:32:27.302+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-16T18:32:27.303+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-16T18:32:27.327+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO SparkContext: Successfully stopped SparkContext
[2024-10-16T18:32:27.327+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO ShutdownHookManager: Shutdown hook called
[2024-10-16T18:32:27.328+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-fa27cc66-d03c-43e1-acf6-1d395ef3fb13
[2024-10-16T18:32:27.335+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-fa27cc66-d03c-43e1-acf6-1d395ef3fb13/pyspark-620f2bde-634f-4540-a360-6e6a22cf6648
[2024-10-16T18:32:27.340+0000] {subprocess.py:93} INFO - 24/10/16 18:32:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-6eff7055-067c-464c-8ea1-bc09b6830c0d
[2024-10-16T18:32:27.426+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-16T18:32:27.438+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-16T18:32:27.451+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=LoadWebScraping, task_id=submit_spark_job, run_id=manual__2024-10-16T18:32:11.550553+00:00, execution_date=20241016T183211, start_date=20241016T183212, end_date=20241016T183227
[2024-10-16T18:32:27.469+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T18:32:27.470+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 98 for task submit_spark_job (Bash command failed. The command returned a non-zero exit code 1.; 270)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-16T18:32:27.519+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-16T18:32:27.534+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T18:32:27.538+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
