[2024-10-04T20:51:33.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-04T20:51:34.001+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SitesWebScraping.Web_Extraction_kabum manual__2024-10-04T20:51:31.214657+00:00 [queued]>
[2024-10-04T20:51:34.009+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SitesWebScraping.Web_Extraction_kabum manual__2024-10-04T20:51:31.214657+00:00 [queued]>
[2024-10-04T20:51:34.010+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-04T20:51:34.025+0000] {taskinstance.py:2888} INFO - Executing <Task(OperatorSiteB): Web_Extraction_kabum> on 2024-10-04 20:51:31.214657+00:00
[2024-10-04T20:51:34.030+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2274) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-04T20:51:34.031+0000] {standard_task_runner.py:72} INFO - Started process 2275 to run task
[2024-10-04T20:51:34.031+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'SitesWebScraping', 'Web_Extraction_kabum', 'manual__2024-10-04T20:51:31.214657+00:00', '--job-id', '1082', '--raw', '--subdir', 'DAGS_FOLDER/DagWebScraping.py', '--cfg-path', '/tmp/tmpxfds5va6']
[2024-10-04T20:51:34.034+0000] {standard_task_runner.py:105} INFO - Job 1082: Subtask Web_Extraction_kabum
[2024-10-04T20:51:34.078+0000] {task_command.py:467} INFO - Running <TaskInstance: SitesWebScraping.Web_Extraction_kabum manual__2024-10-04T20:51:31.214657+00:00 [running]> on host f8603ea05473
[2024-10-04T20:51:34.167+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SitesWebScraping' AIRFLOW_CTX_TASK_ID='Web_Extraction_kabum' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T20:51:31.214657+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T20:51:31.214657+00:00'
[2024-10-04T20:51:34.170+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-04T20:53:06.763+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteBase.py", line 84, in execute
    self.ExtractDates()
  File "/opt/airflow/operators/OperatorSiteB.py", line 32, in ExtractDates
    return super().ExtractDates()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteBase.py", line 53, in ExtractDates
    self._ProcessamentoBeautifulSoup(html, url)
  File "/opt/airflow/operators/OperatorSiteB.py", line 40, in _ProcessamentoBeautifulSoup
    main = clas.find('main', class_='sc-68afdc85-13 eTXlUT')
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
[2024-10-04T20:53:06.779+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=SitesWebScraping, task_id=Web_Extraction_kabum, run_id=manual__2024-10-04T20:51:31.214657+00:00, execution_date=20241004T205131, start_date=20241004T205134, end_date=20241004T205306
[2024-10-04T20:53:06.794+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-04T20:53:06.795+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1082 for task Web_Extraction_kabum ('NoneType' object has no attribute 'find'; 2275)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteBase.py", line 84, in execute
    self.ExtractDates()
  File "/opt/airflow/operators/OperatorSiteB.py", line 32, in ExtractDates
    return super().ExtractDates()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteBase.py", line 53, in ExtractDates
    self._ProcessamentoBeautifulSoup(html, url)
  File "/opt/airflow/operators/OperatorSiteB.py", line 40, in _ProcessamentoBeautifulSoup
    main = clas.find('main', class_='sc-68afdc85-13 eTXlUT')
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
[2024-10-04T20:53:06.849+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-04T20:53:06.858+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
