[2024-11-04T11:02:41.431+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:02:41.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:02:41.437+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:02:41.436+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:02:41.469+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:02:41.465+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:02:41.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:02:41.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.121 seconds
[2024-11-04T11:03:12.458+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:03:12.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:03:12.462+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:12.461+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:03:12.477+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:12.469+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:03:12.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:03:12.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.050 seconds
[2024-11-04T11:03:42.654+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:03:42.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:03:42.659+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:42.658+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:03:42.672+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:03:42.668+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:03:42.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:03:42.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.048 seconds
[2024-11-04T11:04:13.785+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:04:13.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:04:13.789+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:13.789+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:04:13.800+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:13.797+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:04:13.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:04:13.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.043 seconds
[2024-11-04T11:04:45.211+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:04:45.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:04:45.214+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:45.214+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:04:45.240+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:04:45.232+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:04:45.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:04:45.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.202 seconds
[2024-11-04T11:05:15.899+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:05:15.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:05:15.903+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:15.903+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:05:15.920+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:15.916+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:05:15.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:05:15.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.064 seconds
[2024-11-04T11:05:46.307+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:05:46.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:05:46.311+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:46.310+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:05:46.326+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:05:46.324+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:05:46.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:05:46.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.050 seconds
[2024-11-04T11:06:16.428+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:06:16.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:06:16.432+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:16.431+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:06:16.446+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:16.442+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:06:16.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:06:16.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.046 seconds
[2024-11-04T11:06:46.850+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:06:46.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:06:46.853+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:46.853+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:06:46.866+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:06:46.862+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:06:46.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:06:46.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.042 seconds
[2024-11-04T11:07:17.260+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:07:17.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:07:17.264+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:17.264+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:07:17.280+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:17.276+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:07:17.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:07:18.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.775 seconds
[2024-11-04T11:07:48.660+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:07:48.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:07:48.666+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:48.665+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:07:48.684+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:07:48.679+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:07:48.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:07:48.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.057 seconds
[2024-11-04T11:08:18.937+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:08:18.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:08:18.941+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:18.941+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:08:18.957+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:18.952+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:08:18.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:08:18.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.051 seconds
[2024-11-04T11:08:49.473+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:08:49.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:08:49.478+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:49.478+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:08:49.501+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:08:49.497+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:08:49.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:08:49.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.080 seconds
[2024-11-04T11:09:20.144+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:09:20.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:09:20.147+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:20.147+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:09:20.159+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:20.156+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:09:20.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:09:20.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.045 seconds
[2024-11-04T11:09:50.541+0000] {processor.py:186} INFO - Started process (PID=416) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:09:50.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:09:50.548+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:50.548+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:09:50.562+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:09:50.559+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:09:50.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:09:50.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.069 seconds
[2024-11-04T11:10:21.234+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:10:21.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:10:21.239+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:21.239+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:10:21.257+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:21.253+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:10:21.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:10:21.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.052 seconds
[2024-11-04T11:10:51.760+0000] {processor.py:186} INFO - Started process (PID=466) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:10:51.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:10:51.764+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:51.763+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:10:51.780+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:10:51.776+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:10:51.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:10:51.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.060 seconds
[2024-11-04T11:11:22.149+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:11:22.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:11:22.156+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:22.155+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:11:22.169+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:22.165+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:11:22.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:11:22.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.047 seconds
[2024-11-04T11:11:52.845+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:11:52.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:11:52.848+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:52.847+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:11:52.867+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:11:52.863+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:11:52.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:11:53.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.561 seconds
[2024-11-04T11:12:24.129+0000] {processor.py:186} INFO - Started process (PID=545) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:12:24.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:12:24.133+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:24.133+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:12:24.154+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:24.151+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:12:24.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:12:24.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.058 seconds
[2024-11-04T11:12:54.954+0000] {processor.py:186} INFO - Started process (PID=571) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:12:54.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:12:54.958+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:54.957+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:12:54.972+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:12:54.968+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:12:54.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:12:54.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.046 seconds
[2024-11-04T11:13:25.683+0000] {processor.py:186} INFO - Started process (PID=596) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:13:25.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:13:25.686+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:25.686+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:13:25.699+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:25.695+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:13:25.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:13:25.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.045 seconds
[2024-11-04T11:13:55.785+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:13:55.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:13:55.788+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:55.788+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:13:55.809+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:13:55.805+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:13:55.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:13:55.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.054 seconds
[2024-11-04T11:14:26.751+0000] {processor.py:186} INFO - Started process (PID=646) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:14:26.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:14:26.754+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:26.754+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:14:26.767+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:26.764+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:14:26.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:14:26.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.044 seconds
[2024-11-04T11:14:57.633+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:14:57.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:14:57.637+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:57.636+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:14:57.649+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:14:57.646+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:14:57.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:14:57.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.041 seconds
[2024-11-04T11:15:28.692+0000] {processor.py:186} INFO - Started process (PID=696) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:15:28.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:15:28.697+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:28.696+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:15:28.715+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:28.708+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:15:28.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:15:28.754+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.072 seconds
[2024-11-04T11:15:58.813+0000] {processor.py:186} INFO - Started process (PID=721) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:15:58.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:15:58.817+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:58.817+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:15:58.832+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:15:58.829+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:15:58.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:15:58.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.047 seconds
[2024-11-04T11:16:29.871+0000] {processor.py:186} INFO - Started process (PID=747) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:16:29.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:16:29.876+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:16:29.875+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:16:29.890+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:16:29.887+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:16:29.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:16:29.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.047 seconds
[2024-11-04T11:17:00.826+0000] {processor.py:186} INFO - Started process (PID=772) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:17:00.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:17:00.842+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:17:00.842+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:17:00.867+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:17:00.861+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:17:00.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:17:00.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.085 seconds
[2024-11-04T11:17:31.011+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/hooks.py
[2024-11-04T11:17:31.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/hooks.py for tasks to queue
[2024-11-04T11:17:31.015+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:17:31.015+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/hooks.py
[2024-11-04T11:17:31.031+0000] {logging_mixin.py:190} INFO - [2024-11-04T11:17:31.028+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/hooks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hooks.py", line 4, in <module>
    from airflow.providers.postgres.hook.postgres import PostgressHook
ModuleNotFoundError: No module named 'airflow.providers.postgres.hook'
[2024-11-04T11:17:31.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/hooks.py
[2024-11-04T11:17:31.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/hooks.py took 0.051 seconds
